FROM python:3.7
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1
RUN mkdir /code
WORKDIR /code
COPY requirements /requirements
RUN pip install -r /requirements/test.txt
COPY . /code/

#ENTRYPOINT ["python", "manage.py"]
#CMD ["test"]
